#!/bin/bash

mkdir /mnt/disks/sec/prod /mnt/disks/sec/test /mnt/disks/sec/dev
chown brlife:brlife /mnt/disks/sec/*

mkdir /home/brlife/.ssh
touch /home/brlife/.ssh/authorized_keys
chmod 700 /home/brlife/.ssh
chmod 600 /home/brlife/.ssh/authorized_keys
chown brlife:brlife /home/brlife/.ssh
chown brlife:brlife /home/brlife/.ssh/authorized_keys

echo "#Public key to allow access to this resource through (gcp-slurm1)
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQClYwDOJ8AHNuGthVnugZcg6ZKSsGJxlQGmYM77dE8dzMFJuKQbwkub3UTFbad6tsdHl5QAz1DcaMka+J4LneUDIolvzJB3lLv8+qYNFyY9SunZynr2UvRW3S4bYOHQJWtYeU87qY98HMdFS9YdvSJv5N+qIwMTRUMhAVosSvIXObPjURmXcOFfrb8ZyQDz2DFP4saF10jWJcF+08ufu6KQmhE/HmO1HjCvVUG/9KC4pRQhMlMDkBuEkrXXqLIWucbq9InCDyZ8oVFeJl3owtqvt3pB39ctLHZukj/7ymbs2j9JFMCDhaBlBijEWkil9Y5wu9le4rjwZnzwwZbShHFN brainlife.io(gcp-slurm1)
" >> /home/brlife/.ssh/authorized_keys

echo "#Public key to allow access to this resource through (gcp-slurm1)
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCvSseUohZnwpb7ngEZWo+2mINp0Oso/SAI8ps7t3SyJgEmkIU3vXIJYuzj/m8z3xfWAydWEa1hIQfR03lnykiM5QEJAUMZNIWwnsN8kToj3bNyBeLu8IAkBDDXXsoTXGNnxPoVZOygWiM1GaIt9TOjrYv72KS0zvrQ43BYAvktrHPqv7sol40OQEitKeMp1MdpNz57PiuzYRWgB/qCMEW3Q0tMo3PQ3ovYknzDIDeBBQ08WJUTa3q7babmqMlESNHmGaMThVJy6uoxr6n0bxRsNsfPI6VY8tJNxKM3DYT9LMhXwcxL8KHjil9N6dyGYVsjuORqGvMXUa4/BRundtNr test.brainlife.io(gcp-slurm1)
" >> /home/brlife/.ssh/authorized_keys

echo "#Public key to allow access to this resource through (gcp-slurm1)
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDua1m/xP+hXKMW4ixoHjk7aQA1iuJdUFGDBOAwkYKzXOgpc3TDY91SgOhGv+ycYE5vQfXeBq/AXtq1PPvSuvveYN5Q79M3vvjKgzwOQ3kvvO4BiZkD/o6SrQajcnlukn3+BT9bNK+Kl6E0dSV98uvd2BjLkrpRfZyimr8Mir2F7N6PZ7zte1OclturTw/R1oAY7ictAdId9tv91redQEKJ/Jfdv2GB5yUVbANVuX6bOFikga+N4q28nGtrT9ju2VkYOZA8As8lZMDuIkaXj1RzHaR2PSPHi6PtFlxUd6LoDm1i14SIhVENLdDU4YytHqYEYZEkbIRHl4sRB+JUNUrN dev1.soichi.us(gcp-slurm1)
" >> /home/brlife/.ssh/authorized_keys

echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQChls21avMZyOuO+g/oAALpahtVhULAJHsCgY6EHBtWLdcN3hTrf6mDtYMooL8mChtCCNSYwI35VDNx7WFhbB7+y0CTcAiqvK3sYj9aAD0aamvx7ycTqte9Kq6+s/j8qzJPbPiaO1UOdy1Fd+rfPFZnzuKfPzeIXQsMF4rh3pjLO7i8KLaJyKjvpVelsJUHqRoVGlowPvjj/2wUxNg66+QPIdKWFu0BMbvB0Hea8WPGcEvPECprbPTJjEBSwK/SPtGMjvK3eYYdFt1DZpGBruFkOWrFDeym+DmSiwJmSY3gN0JpvniMELv/Dqitf4PaH+qTqANYS7nR4xF4zhD+rO1L hayashis@home
" >> /home/brlife/.ssh/authorized_keys

