#!/bin/bash

yum install -y libarchive-devel squashfs-tools

VERSION=2.6.1
wget https://github.com/singularityware/singularity/releases/download/$VERSION/singularity-$VERSION.tar.gz
tar xvf singularity-$VERSION.tar.gz
cd singularity-$VERSION
./configure --prefix=/usr/local
make
sudo make install

sed -i 's/^\(mount hostfs = no\)$/\mount hostfs = yes/' /usr/local/etc/singularity/singularity.conf

